default_agent: relu_agent
agents:
  relu_agent:
    name: relu_agent
    entrypoint: /home/michael/Downloads/agentic/faultcast_agentcore.py
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/michael/Downloads/agentic
    aws:
      execution_role: arn:aws:iam::771826808190:role/faultcast-agentcore-execution-dev
      execution_role_auto_create: false
      account: '771826808190'
      region: eu-west-1
      ecr_repository: 771826808190.dkr.ecr.eu-west-1.amazonaws.com/bedrock-agentcore-relu_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: relu_agent-K1lW4rCNbV
      agent_arn: arn:aws:bedrock-agentcore:eu-west-1:771826808190:runtime/relu_agent-K1lW4rCNbV
      agent_session_id: 3621d5d0-d91d-444b-83ac-e6fec65661dd
    codebuild:
      project_name: bedrock-agentcore-relu_agent-builder
      execution_role: arn:aws:iam::771826808190:role/AmazonBedrockAgentCoreSDKCodeBuild-eu-west-1-6ecdc4c2e0
      source_bucket: bedrock-agentcore-codebuild-sources-771826808190-eu-west-1
    memory:
      mode: STM_ONLY
      memory_id: relu_agent_mem-6AgcKoCvXz
      memory_arn: arn:aws:bedrock-agentcore:eu-west-1:771826808190:memory/relu_agent_mem-6AgcKoCvXz
      memory_name: relu_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
